### ISSUE TITLE
Web page is down

### ISSUE THREAD

**Issue by magiblot** [Fugiman/api.diff.pics#14]
I don't know if this is the right place to ask, but will the site return to normality?
Thank you very much.

**Comment by Idearum** [comment]
I've noticed the same. Some comparisons work, others don't.

Working: https://diff.pics/ufO6jl4P1AHe/1
Non-working: https://diff.pics/rI3rlfnYA9wt/1

**Comment by Fugiman** [comment]
Hey there, sorry for the late response. As you may have noticed I've been making a large number of changes to the site.

- [x] Changed the upload page to use Vue.js instead of spaghetti jQuery
- [x] Add preview mode to the upload page
- [x] Changed the comparison page to not use javascript at all
- [x] Generate zip files on comparison creation rather than at-request
- [x] Use thumbnail images for swapping within a comparison to avoid downloading 10MB images for no reason
- [x] Rewrite python server in golang
- [x] Use MySQL instead of DynamoDB
- [x] Move static hosting from s3+cloudfront+cloudflare to netlify
- [ ] Move api hosting to a new server

Unfortunately this transition wasn't as smooth as I hoped and the site went down completely for a few days. Then I've been noticing various issues and fixing them as they come up. At this point I think viewing comparisons should work properly, but uploading new ones are still broken as the API server isn't online yet. I'm hoping to get that done this week.

Again, sorry for the downtime, and thank you for your patience.

**Comment by dragons4life** [comment]
Is the website dead or no longer active?

Haven't been able to upload for 3-4 days.  (Chrome/Firefox)

So I am wondering if you are no longer maintaining it or plan to, if this is due to bandwidth why not let people use their own links?

**Comment by Fugiman** [comment]
I'm still maintaining it, looks like there was a bug in the uploading code which I patched tonight, so uploading new comparisons should work again. It's expected that new comparisons should take 5-10min to upload with the new system, which while not great enables viewing comparisons to load much faster.

As far as I can tell everything should now be working properly so I'm going to close this issue. If you find any other problems with the new site please open another issue, reply to this one, or ping me on [twitter](https://twitter.com/fugiman) as I do want this to keep working.

**Comment by dragons4life** [comment]
@Fugiman No problem, however the website still isn't allowing me to upload, keeps giving me an error.

http://0x0.st/CLx.mp4 (This is on chrome)

**Comment by Fugiman** [comment]
Oh, huh, should be fixed now.

**Comment by dragons4life** [comment]
@Fugiman This time it just stays "uploading".

**Comment by Fugiman** [comment]
OK, everything should be fixed for real and creating comparisons should be a _lot_ faster. Let me know if you still see issues.

**Comment by dragons4life** [comment]
Yeah, it's working now for me, thanks for going trough the trouble of fixing.
